name: base
channels:
  - nvidia
  - pytorch3d
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch-cuda=12.1
  - pytorch=*=*cuda12.1*
  - pytorch3d
  - pip
  - pip:
    - numpy
    - -r requirements.txt
    - submodules/gaustudio-diff-gaussian-rasterization
    - -e .
